### ISSUE TITLE
Error reading wind data from NetCDF file

### ISSUE THREAD

**Issue by GeoTuxMan** [NOAA-ORR-ERD/PyGnome#102]
Hello !

I try to create a gridded wind mover:

`w_mover=GridWindMover('test1.nc')    
    model.movers += w_mover`

But , I got this error:
[test1.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/7176770/test1.zip)

Error reading wind data from NetCDF fileTraceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyGnome-0.7.0-py3.8-linux-x86_64.egg/gnome/movers/movers.py", line 352, in prepare_for_model_step
    self.mover.prepare_for_model_step(seconds,
  File "gnome/cy_gnome/cy_mover.pyx", line 96, in gnome.cy_gnome.cy_mover.CyMover.prepare_for_model_step
OSError: CyGridWindMover returned an error: -1

Looking forward to your tips !
George

**Comment by ChrisBarker-NOAA** [comment]
Closing due to inactivity -- please post a new issue if you have further questions about this topic.
