### ISSUE TITLE
a error

### ISSUE THREAD

**Issue by lindbergh153** [NOAA-ORR-ERD/PyGnome#110]
I try to run a subsurface blowout simulation and a issue occurred as follows:
================================================================================
Traceback (most recent call last):
  File "D:/For_GNOME/testing.py", line 35, in <module>
    spill = gs.subsurface_plume_spill(num_elements=8000,
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\spill\spill.py", line 678, in subsurface_plume_spill
    retv = Spill(release=release,
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\spill\spill.py", line 154, in __init__
    self.substance = substance
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\spill\spill.py", line 210, in substance
    self._substance = GnomeOil.get_GnomeOil(val)
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\spill\gnome_oil.py", line 309, in get_GnomeOil
    return GnomeOil(oil_info)
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\spill\gnome_oil.py", line 206, in __init__
    super_kwargs = self._init_from_json(**kwargs)
TypeError: _init_from_json() missing 16 required keyword-only arguments: 'api', 'pour_point', 'solubility', 'bullwinkle_fraction', 'emulsion_water_fraction_max', 'densities', 'density_ref_temps', 'density_weathering', 'kvis', 'kvis_ref_temps', 'kvis_weathering', 'mass_fraction', 'boiling_point', 'molecular_weight', 'component_density', and 'sara_type'

**Comment by ChrisBarker-NOAA** [comment]
I"d have to see the script that caused this error -- but we've refactored how a GnomeOIl can be created. The options are to pass in the name of one of the sample oils, e.g.:

gs.GnomeOil('oil_ans_mp')

Or to pass in a JSON file with oil data:

gs.GnomeOil(filename='alaska-north-slope_AD00020.json')

You can get compatible oil records from: https://adios/orr.noaa.gov

**Comment by ChrisBarker-NOAA** [comment]
Closing due to inactivity -- please post a new issue if you have further questions about this topic.
