### ISSUE TITLE
Problem with the use of multiple current mover files

### ISSUE THREAD

**Issue by rsbragio** [NOAA-ORR-ERD/PyGnome#118]
Hi,
I am having problems in using multiple current mover files in PyGnome. I have several large HYCOM current files in my simulation. I tested using only two of them, named 'HYCOM20190715.nc' and 'HYCOM20190716.nc' but did not succeed. I tried three ways of inputting the files in PyGnome, which are:

a) The first trial was with command GridCurrent.from_netCDF:
c_mover = GridCurrent.from_netCDF(['./HYCOM20190715.nc','./HYCOM20190716.nc'])
model.movers += c_mover

The error message is:
Traceback (most recent call last):
File "...\anaconda3\envs\gnome\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
File "...\run_pygnome.py", line 61, in <module>
    c_mover = GridCurrent.from_netCDF(['./HYCOM20190715.nc','./HYCOM20190716.nc'])
File "...\anaconda3\envs\gnome\lib\site-packages\pygnome-1.1.0-py3.8-win-amd64.egg\gnome\environment\gridded_objects_base.py", line 860, in from_netCDF
    var.init_from_netCDF(*args, **kwargs)
File "...\anaconda3\envs\gnome\lib\site-packages\pygnome-1.1.0-py3.8-win-amd64.egg\gnome\environment\gridded_objects_base.py", line 766, in init_from_netCDF
    ds = dg = get_dataset(grid_file)
File "...\anaconda3\envs\gnome\lib\site-packages\gridded\utilities.py", line 348, in get_dataset
    return nc4.MFDataset(ncfile)
File "src\netCDF4\_netCDF4.pyx", line 6214, in netCDF4._netCDF4.MFDataset.__init__
OSError: master dataset ./HYCOM20190715.nc does not have a aggregation dimension

b) Based on this error, I used the command MFDataset to define time as the aggregation dimension:
f=MFDataset('./HYCOM2019071*.nc', aggdim='time')
time = f['time'][:]
print(time)
c_mover = GridCurrent.from_netCDF(filename=f)
model.movers += c_mover

By printing the variable time, I checked that the time appears correctly, joining the times of the two files, but the following error appeared:

Traceback (most recent call last):
File "src\netCDF4\_netCDF4.pyx", line 6428, in netCDF4._netCDF4._Variable.__getattr__
KeyError: 'name'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "...\anaconda3\envs\gnome\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
File "...\run_pygnome.py", line 67, in <module>
    c_mover = GridCurrent.from_netCDF(filename=f)
File "...\anaconda3\envs\gnome\lib\site-packages\pygnome-1.1.0-py3.8-win-amd64.egg\gnome\environment\gridded_objects_base.py", line 860, in from_netCDF
    var.init_from_netCDF(*args, **kwargs)
File "...\anaconda3\envs\gnome\lib\site-packages\pygnome-1.1.0-py3.8-win-amd64.egg\gnome\environment\gridded_objects_base.py", line 799, in init_from_netCDF
    depth = Depth.from_netCDF(grid_file,
File "...\anaconda3\envs\gnome\lib\site-packages\pygnome-1.1.0-py3.8-win-amd64.egg\gnome\environment\gridded_objects_base.py", line 388, in from_netCDF
    return gridded.depth.Depth.from_netCDF(*args, **kwargs)
File "...\anaconda3\envs\gnome\lib\site-packages\gridded\depth.py", line 452, in from_netCDF
    cls = Depth._get_depth_type(df, depth_type, topology, _default_types)
File "...\anaconda3\envs\gnome\lib\site-packages\gridded\depth.py", line 500, in _get_depth_type
    L_Depth.from_netCDF(dataset=dataset)
File "...\anaconda3\envs\gnome\lib\site-packages\gridded\depth.py", line 131, in from_netCDF
    vname = cls._gen_varname(filename, dataset, [tn], [tln])
File "...\anaconda3\envs\gnome\lib\site-packages\gridded\depth.py", line 83, in _gen_varname
    if var.name == n:
File "src\netCDF4\_netCDF4.pyx", line 6430, in netCDF4._netCDF4._Variable.__getattr__
AttributeError: name

c) The last method that I have tried was according to Reference Zelenke et al. (GNOME technbical Documentation page 53), by creating a txt file:

current_MasterFile = get_datafile(os.path.join(base_dir, 'HYCOM_MasterFile.txt'))
c_mover = GridCurrentMover(current_MasterFile)
model.movers += c_mover

The txt file is:
NetCDF Files
[FILE]  :HYCOM20190715.nc
[FILE]  :HYCOM20190716.nc

The error message is:
Traceback (most recent call last):
File "...\anaconda3\envs\gnome\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
File "...\run_pygnome.py", line 74, in <module>
    c_mover = GridCurrentMover(current_MasterFile)
File "...\anaconda3\envs\gnome\lib\site-packages\pygnome-1.1.0-py3.8-win-amd64.egg\gnome\movers\current_movers.py", line 512, in __init__
    self.mover.text_read(filename, topology_file)
File "gnome\cy_gnome\cy_gridcurrent_mover.pyx", line 60, in gnome.cy_gnome.cy_gridcurrent_mover.CyGridCurrentMover.text_read
OSError: GridCurrentMover_c.TextRead returned an error.
ResolvePath(): Could not resolve path

I appretiate if anyone can help in any of theses issues, or in any method that can allow using multiple current mover files.
Thanks.

**Comment by jay-hennen** [comment]
GridCurrentMover won't be able to handle these files. That is a (very) old and unofficially deprecated Mover. The HYCOM files won't have the expected names and format.

Your corrective action to failure a) was the right move. That should have been enough to get it working but I have to apologize for the problems you had in the Depth object. It never received the level of scrutiny and TLC that the Grid and Time have received. That being said, I intend to provide that scrutiny sometime in the next few weeks.

There are two ways you can try to workaround this in the interim. First way would be to remove the depth dimension from your files, which would be the most reliable way forward. And, if you are skilled with .nc manipulation, probably the easiest.

Second way would be to build a L_Depth object manually and provide it to the `.from_netCDF` function as follows: `GridCurrent.from_netCDF(filename=f, depth=d)` This may let you use the files as they are but will likely be more difficult and will require looking at the `gridded.depth.L_Depth` code.

**Comment by rsbragio** [comment]
Hi Jay,
Thanks very much for the answer. I would like to make two questions about the first way that you recommended for solving the problem:
1) if I remove the depth dimension from my files, does this mean that PyGnome is not going to consider the current velocities at other depths? The case I intend to simulate should have the oil moving between the surface and 20 meters depth and I expected to use the velocities in several depth levels from the HYCOM file. 
2) Removing the depth dimension would be the same of downloading the HYCOM file with only the velocities at surface?
Best regards,
Ricardo Sbragio


    Em segunda-feira, 2 de maio de 2022 15:35:50 BRT, jay-hennen ***@***.***> escreveu:  
 
 


GridCurrentMover won't be able to handle these files. That is a (very) old and unofficially deprecated Mover. The HYCOM files won't have the expected names and format.

Your corrective action to failure a) was the right move. That should have been enough to get it working but I have to apologize for the problems you had in the Depth object. It never received the level of scrutiny and TLC that the Grid and Time have received. That being said, I intend to provide that scrutiny sometime in the next few weeks.

There are two ways you can try to workaround this in the interim. First way would be to remove the depth dimension from your files, which would be the most reliable way forward. And, if you are skilled with .nc manipulation, probably the easiest.

Second way would be to build a L_Depth object manually and provide it to the .from_netCDF function as follows: GridCurrent.from_netCDF(filename=f, depth=d) This may let you use the files as they are but will likely be more difficult and will require looking at the gridded.depth.L_Depth code.

**Comment by rsbragio** [comment]
Just to close the issue with the solution of the problem, PyGnome worked well using only one current input file. To concatenate the files, I downloaded them in .nc4 format from HYCOM website for the whole time period and for each depth that I intended to simulate. The commands I used to concatenate the file, based on the depth, are:

  #INITIAL SETUP
    import netCDF4 as nc
    import numpy
    import xarray

   #COMBINE NETCDF FILES
    ds = xarray.open_mfdataset('HYCOM_*.nc4', combine = 'nested', concat_dim="depth")
    ds.to_netcdf('HYCOMcombined.nc', format = "NETCDF3_64BIT")
    
   #CLOSE FILES
    ds.close()
