### ISSUE TITLE
Problem with installation of PyGnome

### ISSUE THREAD

**Issue by rsbragio** [NOAA-ORR-ERD/PyGnome#123]
Hi, I am trying to install PyGnome model and, although it seems to complete the installation,  I had the following errors when running the script from Spyder:

c:\users\rs\pygnome\py_gnome\gnome\__init__.py:62: UserWarning: ERROR: The gridded package, version >= 0.3.0 needs to be installed: 
  warnings.warn(msg)
Traceback (most recent call last):
  File "C:\Users\RS\anaconda3\envs\gnome\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
  File "c:\users\rs\documents\usp-posdoc\costabrasil\run_pygnome.py", line 9, in <module>
    import gnome.scripting as gs
  File "c:\users\rs\pygnome\py_gnome\gnome\__init__.py", line 136, in <module>
    from . import (environment,
  File "c:\users\rs\pygnome\py_gnome\gnome\environment\__init__.py", line 5, in <module>
    from .environment import Environment, env_from_netCDF, ice_env_from_netCDF
  File "c:\users\rs\pygnome\py_gnome\gnome\environment\environment.py", line 17, in <module>
    from gnome.persist import base_schema
  File "c:\users\rs\pygnome\py_gnome\gnome\persist\__init__.py", line 19, in <module>
    from .extend_colander import (TupleSchema, SequenceSchema, SchemaNode,
  File "c:\users\rs\pygnome\py_gnome\gnome\persist\extend_colander.py", line 14, in <module>
    import gnome.basic_types
  File "c:\users\rs\pygnome\py_gnome\gnome\basic_types.py", line 24, in <module>
    from .cy_gnome import cy_basic_types as cbt
ImportError: DLL load failed while importing cy_basic_types: The specified procedure could not be found.

When running directly using the command "python name_of_script.py", the following error message came:
    from gnome.spill import point_line_release_spill
    ModuleNotFoundError: No module named 'gnome.spill'

I am following the installation procedure from https://gnome.orr.noaa.gov/doc/pygnome/installing.html#building-installing-pygnome-with-the-conda-package-manager, but it seems that some packages are not being installed correctly.

I would like to ask for your help in this issue.

Thanks.

**Comment by jay-hennen** [comment]
Just to verify, are you in the 'gnome' environment you created in those instructions? Usually these sort of 'not found' problems after installation are due to either your terminal or your installation not being in the correct environment.

**Comment by rsbragio** [comment]
Hi Jay,
Yes. In both trials, I ran the script from inside the Gnome environment.

**Comment by AmyMacFadyen** [comment]
gnome.spill was renamed to gnome.spills for consistency. sorry, for that inconvenience and lack of backwards compatibility with existing scripts.

**Comment by rsbragio** [comment]
Hy Amy,
Thanks very much for the information. I tried renaming gnome.spills to gnome.spill, but the error continues. Shall I wait for some correction on the installation files, or shall I try something else to correct?

**Comment by rsbragio** [comment]
I am not sure about what branch I am working in. I followed the instructions from https://gnome.orr.noaa.gov/doc/pygnome/installing.html. 

During installation, I have not seen any option about using any other branch. In fact, I do not know what a branch is.  The command I have used for importing gnome was: 
git clone https://github.com/NOAA-ORR-ERD/PyGnome.git

After cloning the directory, I created the PyGnome environment using:
conda create -n gnome --file conda_requirements.txt

It seems that all files were downloaded correctly.

**Comment by ChrisBarker-NOAA** [comment]
In order to use PYGNOME you must:

1) Have all the supported libraries it needs -- the easieast way to do that is to use conda and miniforge.
2) You need to compile the pacakge itself.

This is laid out in:

https://gnome.orr.noaa.gov/doc/pygnome/installing.html

You likely want to use the "main" branch -- which you will get be default if you "git clone" -- or is you download the Latest Release:

https://github.com/NOAA-ORR-ERD/PyGnome/releases
