### ISSUE TITLE
Can't load GridCurrent

### ISSUE THREAD

**Issue by gab1092** [NOAA-ORR-ERD/PyGnome#135]
Hello! I can't load the module GridCurrentMover, I install pygnome a few days ago, with the new instalation I can't use GridCurrentMover the error is as follows, somebody can help me please?

from gnome.movers import GridCurrentMover

from gnome.movers import GridCurrent
Traceback (most recent call last):

  File "/tmp/ipykernel_711923/1284827270.py", line 1, in <cell line: 1>
    from gnome.movers import GridCurrent

ImportError: cannot import name 'GridCurrent' from 'gnome.movers' (/home/gabriela/PyGnome/py_gnome/gnome/movers/__init__.py)

**Comment by coconnor8** [comment]
The GridCurrentMover has been renamed c_GridCurrentMover in the latest
version.
If you look in the file listed in the error message you will see the
available mover names.

**Comment by ChrisBarker-NOAA** [comment]
Also note that you are having trouble importing GridCurrent from the Movers module -- but GridCurrent is not a mover,  so not there. Most of the time you don't need to work directly with the GridCurrent -- you can probably simply use the Mover.

Also, we have made it a bit easier t find all these object by putting them in the "scripting" namespace, so you can do:

import gnome.scripting as gs

mover = gs.PyGridCurrentMover(....)

See: 
https://gnome.orr.noaa.gov/doc/pygnome/scripting/index.html

(not complete but it should be helpful)

**Comment by gab1092** [comment]
Thank you for your help! Another doubt, how I can import a list of files? I' trying with the text file but I received an error, and I tried with a list of files in python but I can't able to load all the files, I'm trying with data form NCOM and HYCOM, but when I load a list of netcdf files of HYCOM the error is: 

from gnome.movers import PyCurrentMover

c_mover=PyCurrentMover(files)
Traceback (most recent call last):

  File "/tmp/ipykernel_1505281/2943399570.py", line 1, in <cell line: 1>
    c_mover=PyCurrentMover(files)

  File "/home/gabriela/PyGnome/py_gnome/gnome/movers/py_current_movers.py", line 106, in __init__
    self.current = GridCurrent.from_netCDF(filename=self.filename,

  File "/home/gabriela/PyGnome/py_gnome/gnome/environment/gridded_objects_base.py", line 893, in from_netCDF
    var.init_from_netCDF(*args, **kwargs)

  File "/home/gabriela/PyGnome/py_gnome/gnome/environment/gridded_objects_base.py", line 798, in init_from_netCDF
    ds = dg = get_dataset(grid_file)

  File "/home/gabriela/anaconda3/envs/gnome/lib/python3.8/site-packages/gridded/utilities.py", line 353, in get_dataset
    return nc4.MFDataset(ncfile)

  File "src/netCDF4/_netCDF4.pyx", line 6805, in netCDF4._netCDF4.MFDataset.__init__

OSError: master dataset /media/gabriela/WDBlue_2/CIGOM/hycom_4km/HYCOM-DAILY-20210829.nc does not have a aggregation dimension


Thank you!
