### ISSUE TITLE
ValueError: Not enough LEs: Number of LEs must at least be equal to the number of timesteps in the release

### ISSUE THREAD

**Issue by Gronohibari12** [NOAA-ORR-ERD/PyGnome#166]
Hello im trying to fix this error. 
It happens in a long time simulation (6 months) where i want to simulate some spills that i load into the model through a points shapefile. Ideally i would like each spill to release around 3 LE every hour as they are a lot. But i have tried to increase the LE and the error persists. This is the full error : 
Traceback (most recent call last):
  File "/home/makis/datatosend/linuxmodel.py", line 117, in <module>
    for step in model:
  File "/home/makis/anaconda3/envs/gnome/lib/python3.10/site-packages/gnome/model.py", line 1278, in __next__
    return self.step()
  File "/home/makis/anaconda3/envs/gnome/lib/python3.10/site-packages/gnome/model.py", line 1163, in step
    self.setup_model_run()
  File "/home/makis/anaconda3/envs/gnome/lib/python3.10/site-packages/gnome/model.py", line 869, in setup_model_run
    sc.prepare_for_model_run(array_types, self.time_step)
  File "/home/makis/anaconda3/envs/gnome/lib/python3.10/site-packages/gnome/spill_container.py", line 819, in prepare_for_model_run
    s.prepare_for_model_run(time_step)
  File "/home/makis/anaconda3/envs/gnome/lib/python3.10/site-packages/gnome/spills/spill.py", line 432, in prepare_for_model_run
    self.release.prepare_for_model_run(timestep)
  File "/home/makis/anaconda3/envs/gnome/lib/python3.10/site-packages/gnome/spills/release.py", line 576, in prepare_for_model_run
    super(PointLineRelease, self).prepare_for_model_run(ts)
  File "/home/makis/anaconda3/envs/gnome/lib/python3.10/site-packages/gnome/spills/release.py", line 357, in prepare_for_model_run
    raise ValueError('Not enough LEs: Number of LEs must at least \
ValueError: Not enough LEs: Number of LEs must at least                 be equal to the number of timesteps in the release

**Comment by ChrisBarker-NOAA** [comment]
The message is what it says -- you don't have enough elements to release at least one every timestep.

If you want 3 every hour, then you would have to have a timestep or 20 minutes or longer, and then you would need:

3 * number_of_hours_of_release elements.

is the release the full 6 months? if so, then that's:

30days * 24 hours * 3 = 2160 elements.

Maybe a few more if you have 32 day months..

If you have a shorter timestep, say 10 minutes, then you'd need twice as many:

4320 elements.

Now that you write this. perhaps we should allow an element to be released, for example, every other timestep -- which used to be legal, but then folks got odd results, with an uneven release: -- i.e. different for each timestep.

HTH,

-CHB

**Comment by Gronohibari12** [comment]
Is this reffering to LE that are released every hour or total LE in the simulation run?
Im pretty sure i have run simulations in the past(shorter around a week) With each spill releasing 2 LE every hour. The number of spills is around 70.

**Comment by ChrisBarker-NOAA** [comment]
> Is this reffering to LE that are released every hour or total LE in the simulation run?

it's referring to the total number of elements in each release. 

Each release (spill) is independent, and it need to release at least 1 element per timestep.

**Comment by Gronohibari12** [comment]
Thanks a lot for the reply! 
I fixed by adding the argument for total LE to be released in the release and the LE per timestep!
