### ISSUE TITLE
PyGridCurrentMover function not availabke.

### ISSUE THREAD

**Issue by dkobashi** [NOAA-ORR-ERD/PyGnome#29]
Dear all,

I installed PyGNOME like a week or two ago on my local computer and it has gnome.movers.py_current_mover.PyGridCurrentMover. Then I installed PyGNOME on another machine (cluster) a couple of days ago and the above function is not available. I created run script based on script_ny_roms.py as I use ROMS output as current input. 

Have you updated the function and Is there any alternative function to use?
The lines I am taking about are the following where url is the OPeNDAP address of  ROMS output history file.
 
    cf = GridCurrent.from_netCDF((url))
    u_mover = PyGridCurrentMover(cf, default_num_method='Euler')
    model.movers += u_mover

Thanks in advance.

DJ Kobashi

**Comment by dkobashi** [comment]
Apparently PyGridCurrentMover has been changed to PyCurrentMover. When I changed it, the model seems to work fine. If that's the case, you can close the case. Please edit the manual to avoid confusion. Thanks, -DJ

**Comment by ChrisBarker-NOAA** [comment]
Yes, that's it-- sorry you had to figure it out.

I'll leave this issue open until we get the docs fixed.

Thanks,

-CHB

On Apr 14, 2017, at 10:07 AM, dkobashi <notifications@github.com> wrote:

Apparently PyGridCurrentMover has been changed to PyCurrentMover. When I
changed it, the model seems to work fine. If that's the case, you can close
the case. Please edit the manual to avoid confusion. Thanks, -DJ

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NOAA-ORR-ERD/PyGnome/issues/29#issuecomment-294192686>,
or mute the thread

**Comment by doronbart** [comment]
Dear all,
given that I do not have a thorough knowledge of Python.
I'm trying to read ROMS output files directly (30 vertical levels on a regular regular grid) of which I attach the header file.
I tried the functions mentioned above:
fn='ocean_his_20180722_0007.nc'
current = GridCurrent.from_netCDF (filename = fn, varnames = ['u', 'v'])
uv_mover = PyCurrentMover (current, default_num_method = 'Euler')
model.movers + = uv_mover

But I still have a series of error messages like:
_File "/home/coast/local/bin/miniconda3/lib/python2.7/site-packages/gridded/utilities.py", line 370, in get_dataset
return nc4.MFDataset(ncfile)
File "netCDF4/_netCDF4.pyx", line 6108, in netCDF4._netCDF4.MFDataset.__init__
TypeError: 'GridCurrent' object does not support indexing_

Do I need to better specify the topology of my grid or is it able to recognize it automatically? Is it a problem with my netcdf output format?
Do you already have a working code with this kind of output?

Thanks in advance for support
Berto
[ocean_his_20180722_0007.nc_header.txt](https://github.com/NOAA-ORR-ERD/PyGnome/files/3689957/ocean_his_20180722_0007.nc_header.txt)

**Comment by jay-hennen** [comment]
Hi there. Your problem is here:
uv_mover = PyCurrentMover (**current**, default_num_method = 'Euler')

PyCurrentMover init first argument is a filename, second argument is an already created current, so it's trying to open the GridCurrent object with netCDF4. It's always best to use keyword arguments whenever possible.

**Comment by doronbart** [comment]
Thank you very much Jay,
I was confused with the syntax of the GridCurrentMover function..

In effect, specifying a filename as the first argument in 'PyCurrentMover' now works. But I'm a bit confused about the usefulness of this filename. If the file to use is already specified by 'fn' what is it for?
How do I load a list of netcdf files with this syntax?
Excuse me for too many boring questions.

Berto

**Comment by jay-hennen** [comment]
We have previous users who expect the Mover API to work that way. That's pretty much it.

To load a list of netCDF files, just pass the filenames into the 'filename' kwarg as a correctly sorted list.

**Comment by doronbart** [comment]
Hi Jay,
I tried to pass a list of files to 'filename' but I can't get the PyCurrentMover function to work:
This is my simple test code

fns=['meteo_ocean1.nc', 'meteo_ocean2']
uv_mover = PyCurrentMover( filename = fns,  default_num_method = 'Euler')

In the case of fn = ['meteo_ocean.nc'], everything works without problems.
I also tried a file containing a list of files as was done with 'GridCurrentMover' function, but it doesn't even work. I tried also with some cycles but I don't solve the problem. The only solution for me is to build a unique netcdf file but in the case of very long simulations it becomes really difficult to manage.

Any suggestions?
thanks,
Berto

**Comment by ChrisBarker-NOAA** [comment]
What error are you getting?

But at a glance, it looks like you need to add a ".nc" to that second filename.

**Comment by doronbart** [comment]
The file without .nc was only a typing error..
In my code it is written correctly and the error that is returned to me is a bit strange:


Traceback (most recent call last):
  File "./larve_v1_draft.py", line 222, in <module>
    model = make_model(image_dir)
  File "./larve_v1_draft.py", line 148, in make_model
    uv_mover = PyCurrentMover(filename = fns,  default_num_method = 'Euler') 
  File "/home/coast/local/bin/miniconda3/lib/python2.7/site-packages/pyGnome-0.6.2-py2.7-linux-x86_64.egg/gnome/movers/py_current_movers.py", line 100, in __init__
    **kwargs)
  File "/home/coast/local/bin/miniconda3/lib/python2.7/site-packages/gridded/variable.py", line 779, in from_netCDF
    grid_topology=grid_topology)
  File "/home/coast/local/bin/miniconda3/lib/python2.7/site-packages/pyGnome-0.6.2-py2.7-linux-x86_64.egg/gnome/environment/gridded_objects_base.py", line 333, in from_netCDF
    return gridded.grids.Grid.from_netCDF(*args, **kwargs)
  File "/home/coast/local/bin/miniconda3/lib/python2.7/site-packages/gridded/grids.py", line 478, in from_netCDF
    c = Grid._load_grid(filename, cls, dataset)
  File "/home/coast/local/bin/miniconda3/lib/python2.7/site-packages/gridded/grids.py", line 428, in _load_grid
    g = grid_type.load_grid(ds)
  File "/home/coast/local/bin/miniconda3/lib/python2.7/site-packages/gridded/pysgrid/sgrid.py", line 114, in load_grid
    sa = SGridAttributes(nc, cls.topology_dimension, topology_var)
  File "/home/coast/local/bin/miniconda3/lib/python2.7/site-packages/gridded/pysgrid/sgrid.py", line 944, in __init__
    self.ncd = NetCDFDataset(self.nc)
  File "/home/coast/local/bin/miniconda3/lib/python2.7/site-packages/gridded/pysgrid/read_netcdf.py", line 131, in __init__
    self._filepath = nc.filepath()
  File "netCDF4/_netCDF4.pyx", line 2335, in netCDF4._netCDF4.Dataset.filepath
  File "netCDF4/_netCDF4.pyx", line 1842, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID

The filename passed as a list o list file has already been tested in PyCurrentMover? Do you have an example code?

**Comment by jay-hennen** [comment]
That looks like a legitimate problem with an older part of our loading code not handling multi files correctly. Until we get to it, you can work around it by doing the following:

from gnome.environment.gridded_objects_base import Grid_S
grid = Grid_S.from_netCDF(filename=fns)
current = GridCurrent.from_netCDF(filename=fns, grid=grid)
mover = PyCurrentMover(current = current)

**Comment by jay-hennen** [comment]
Upon further inspection it appears that the solution I posted above may not be effective. If this is the case unfortunately you may have to simply join the files for the time being.

**Comment by doronbart** [comment]
Hi Jay, in fact the solution you proposed does not solve the problem.
I will be waiting for code updates.

Thanks,
Berto

**Comment by ChrisBarker-NOAA** [comment]
Closing due to inactivity -- please post a new issue if you have further questions about this topic.
