### ISSUE TITLE
Tides help

### ISSUE THREAD

**Issue by Lemcastroro** [NOAA-ORR-ERD/PyGnome#52]
Hi!

I am a beginner, I'm  traying to do a simulation in Pacific ocean , I have tidal data (harmonic constituents) but i don't know how  to enter them into the model, (what format or structure) neither in pygnome nor in gnome.

Thank you for the help,

Best regards,

**Comment by ChrisBarker-NOAA** [comment]
There are two ways to do harmonic constituent tides:
1) use the tidal constituents to scale a "current pattern" -- in this case, you would have a 2D current pattern of, e.g. the flood tide, and then you would scale it by tidal current constituents at a given point.
 - if this is your case, we can give you an example constituent file to use, or you can make one with our tidal program: SHIO

2) you can have a gridded field, with tidal constituents at each node. This is currently not directly supported in GNOME, but we do have some code that will generate a netcdf file with the currents for a particular time range from the constituents. That is still experimental code, so we'd have to point you to it, and you'd have a bit to figure out.

@coconnor8 : maybe you can find docs for the SHIO constituent file format?

**Comment by Lemcastroro** [comment]
The example of the file would help me a lot. :)
I have seen the example of shio file in txt, in the script passamaquoddy.py, but I don't have the topology.
 
I have a grid of currents in nedcdf and I don't know if I can incorporate it in
CurrentCycleMover as curr_file, according to the line of code, or would catsmover be better? what is the difference?

cc_mover = CurrentCycleMover(curr_file, topology_file,
                                 tide=Tide(tide_file))

Sorry if it's a very novice question.

Thanks

**Comment by ChrisBarker-NOAA** [comment]
> I have seen the example of shio file in txt, in the script passamaquoddy.py,

yes, that is the tidal constituents format -- so good start. 

> but I don't have the topology.

That's OK -- it is optional -- it will build the topology for you if it's not there.

> I have a grid of currents in nedcdf and I don't know if I can incorporate it inCurrentCycleMover as curr_file, according to the line of code, or would catsmover be better? what is the difference?

CatsMover is probably what you want:

https://github.com/NOAA-ORR-ERD/PyGnome/blob/master/py_gnome/gnome/movers/current_movers.py#L172

However, the current file it expects is the in-house "CATS" format.

@coconnor8: is there a way to use netcdf? 

Otherwise, we should support that, so I could probably add that feature, or make a translator for you. -- what type of grid is the model you have on? CAn you post an example netcdf file somewhere we can take a look?

**Comment by Lemcastroro** [comment]
Here I attach the netcdf of currents that I am using. These currents are not tidal currents, Should I generate a grid with these currents?

[abril15_16.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/3452147/abril15_16.zip)

I tried using the example txt file (passamaquoddy) directly in my code by changing only the coordinates. I got the following error:

```
Traceback (most recent call last):
  File "script_A_entrante.py", line 113, in <module>
    model = make_model()
  File "script_A_entrante.py", line 82, in make_model
    c_mover = CatsMover(tide=Tide(tide_file))
  File "c:\users\cioh - arope\pygnome\py_gnome\gnome\movers\current_movers.py", line 212, in __init__
    if not os.path.exists(filename):
  File "C:\Users\CIOH - AROPE\Anaconda\envs\gnome\lib\genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

my code is:

`tide_file = get_datafile(os.path.join(base_dir, 'EstesHead.txt'))
    c_mover = CatsMover(tide=Tide(tide_file))
    
    model.movers += c_mover
    model.environment += c_mover.tide `

Thanks a lot
```

**Comment by Lemcastroro** [comment]
other question,

Would it be correct if I use another netcdf file (in addition to the currents file) with the tidal currents grid?

a file like this
[mareaabril2.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/3453555/mareaabril2.zip)

thanks

**Comment by Lemcastroro** [comment]
other question,

Would it be correct if I use another netcdf file (in addition to the currents file) with the tidal currents grid?

A file like this
[mareaabril3.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/3453724/mareaabril3.zip)


thanks

**Comment by Lemcastroro** [comment]
other question,

Would it be correct if I use another netcdf file (in addition to the currents file) with the tidal currents grid?

A file like this
[mareaabril.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/3453772/mareaabril.zip)


thanks

**Comment by ChrisBarker-NOAA** [comment]
I've taken a look at your data files, and they appear to be a time series of currents on a rectangular grid. py_gnome can use these just fine, with the "PyCurrentMover". I"ve enclosed a sample script that uses them.

[test_run.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/3459126/test_run.zip)


Here's the key part:

`model.movers += gs.PyCurrentMover("mareaabril.nc")`

pretty simple, eh?

However, the currents in those files are pretty darn small (~0.01 m/s), so not moving things much.

You mention "tidal currents" -- In that location off the coast of Colombia, I wouldn't expect the tidal currents to be very strong -- at least not at that scale.

Bu tif you are trying to capture the tides, and don't have a full time series, than you need to have a single pattern that you can scale with the tides.

**Comment by ChrisBarker-NOAA** [comment]
Closing due to inactivity -- please post a new issue if you have further questions about this topic.
