### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by moisespr123** [NOAA-ORR-ERD/PyGnome#76]
Hi,

I have additional questions as I've been reading the source code.

1. I'm currently creating a custom BNA file by extracting the data from a global BNA. This is very time consuming, taking between 1-2 minutes. Reading the code, I see the following function: `grid_from_nc(filename)`. Would this read a file to generate the map needed for PyGnome, replacing the use of the BNA? Would the Mask be the land or sea? (Which needs to be 0 and which has to be 1?), Is there a sample file to take a look into it?
2. Instead of using the PyWindMover and PyCurrentMover function, is there a method to pass the Wind and Current arrays without having to intermediately create a netCDF file with this data to pass to PyGnome?

Thanks,
-Moises

**Comment by jay-hennen** [comment]
1. Maybe @ChrisBarker-NOAA can say more on `grid_from_nc` but I believe that is not a working function at this point. Apologies! It is a good idea to subset your BNA geographically and reduce the level of detail if it's too high. The [NOAA GOODS service](https://gnome.orr.noaa.gov/goods/tools/GSHHS/coast_subset) has a pretty good BNA map tool.

2. Yes, it is possible to build environment objects using numpy arrays. It is a fairly involved process though, so be warned. I don't have time at the moment to go into detail, but I can later if you want. Highlighting your specific needs would help me in that regard.

**Comment by ChrisBarker-NOAA** [comment]
> I'm currently creating a custom BNA file by extracting the data from a global BNA. This is very time consuming, taking between 1-2 minutes.

As Jay mentioned, the tools on GOODS can help here:

https://gnome.orr.noaa.gov/goods/tools/GSHHS/coast_subset

We are working on making GOODS a WEb service with a decent API, but in the meantime, you could probably even reverse-engineer the request to get particular map on the fly. Alternatively, the code behind GOODS is mostly here:

https://github.com/NOAA-ORR-ERD/GnomeTools/tree/master/libgoods/libgoods

Thirdly, we'd like to support other file formats for maps: shape, geojson. That's not hard, we jus need to take the time to 
write a bit of code (PR's accepted!) let us know if that would help.

`grid_from_nc(filename)` and related are not well tested, but we can help you get them working if they would be helpful. The idea there is to generate a GNOME map that matches the model grid, rather than being a separate vector map. Be careful here thought, as the "stair stepping" along shoreline can be problematic for particular tracking and beaching.

"is there a method to pass the Wind and Current arrays without having to intermediately create a netCDF file "
AS Jay said, that's doable -- but you essentially have to do most of teh work you'd need to do for a netcdf file anyway. But you should be able to build a gridded.Dataset object directly -- and then pass that to GNOME.

What form do you have the data / grid in now?

**Comment by moisespr123** [comment]
1. Thanks for providing me to the libgoods source code. I'll take a look into it. I see there's a `hycom2bna.py` script that may help into creating a bna file from a netCDF. I work with netCDF files mainly.
2. I'm currently just slicing wind/water velocity from global files to create the netCDF file with just the portion needed for PyGnome to run ([I opened this issue related to this](https://github.com/NOAA-ORR-ERD/PyGnome/issues/74)), and while this works, I was just wondering if there was a way to skip this file generation and just pass the arrays to PyGnome instead of having it open the file and extract it. It may save a few IO operations in my case :-)

**Comment by moisespr123** [comment]
Another question: Does PyGnome allow specifying depths?

**Comment by AmyMacFadyen** [comment]
With respect to libGOODS -- that's something of a half finished project that is not fully functional. In particular, I don't recall if the hycom2bna script was completed. Chris, I think that may have been something you wrote and it is probably grid dependent (i.e. HYCOM is available both in curvilinear and regular grid).

**Comment by ChrisBarker-NOAA** [comment]
Thanks @AmyMacFadyen :: yes, libgoods should be considered. collection of scripts and utilities that may be useful.

With regard to hycom2bna: what is your goal? If you want a map to exactly match a rectangular grid, there is a map type in py_gnome that will do that -- it hasn't been used in a while, but worth a shot. though oddly, I can't find it at the moment :-(

" if there was a way to skip this file generation and just pass the arrays to PyGnome instead of having it open the file and extract it. It may save a few IO operations in my case :-)"

I'm still a bit confused as to where you are getting these arrays? If you are extracting them from the global netcdf files on the fly, then you could simply pass the entire global dataset into py_gnome. It will load teh entire grid, but will only load the data that it needs -- so that may work just fine.

**Comment by ChrisBarker-NOAA** [comment]
with regard to your previous issue -- you may need to adjust the coordinates in the global files (so that's in consitent longitude -- i.e. -180-180 04 0--360.

@jay-hennen:  I think we've added some utilities to py_gnome for this lately -- yes?

**Comment by moisespr123** [comment]
For the last part, I loaded the global NETCDF files but it didn't work.
Maybe because they are formatted as 0-360 rather than -180 to 180? Also,
I'm concatenating them as a single file since each timestep is a different
file.

I'm currently setting up libgoods on my environment to try it.

**Comment by ChrisBarker-NOAA** [comment]
Hmm, I think 0-360 should work, as long as your other data (map, winds) re also 0-360.

And you can pass a list of filenames in, so as not to have to concatenate them ahead of time.

**Comment by moisespr123** [comment]
Thanks, how would a list of filenames be passed? 

I have these 2 lines to open the NetCDF file once it's written:

```
model.movers += gs.PyWindMover(wind_mover_nc_file)
model.movers += gs.PyCurrentMover(curr_mover_nc_file)
```

Would it be adding a loop and make those 2 functions open the files sequentially?

BTW, I got libgoods to run and generate maps. The BNA performance significantly improved!

**Comment by ChrisBarker-NOAA** [comment]
```
model.movers += gs.PyCurrentMover([curr_mover_nc_file1,
                                   curr_mover_nc_file2,
                                   ...
                                   ])
```
should do it

**Comment by moisespr123** [comment]
@ChrisBarker-NOAA , I'll give the `map_from_rectangular_grid_nc_file` function a try. Question: Which area should be the zeros? land or sea? Is there a mask netCDF file readily available I could use?

**Comment by ChrisBarker-NOAA** [comment]
honestly, it's been along time :-)

But I think you want 0 for water, and any anything else is land (usually 1)

Sorry, not example available.

**Comment by moisespr123** [comment]
Hi Chris, 

I have created my mask.nc file. However, I get the following error:

```
map.map_from_rectangular_grid_nc_file('mask.nc') 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/PyGnome/py_gnome/gnome/maps/map.py", line 1563, in map_from_rectangular_grid_nc_file
    grid, lon, lat = grid_from_nc(filename)
  File "/PyGnome/py_gnome/gnome/maps/map.py", line 1517, in grid_from_nc
    nx, ny = lat_var.shape
ValueError: not enough values to unpack (expected 2, got 1)
```

This is my input file details:

```
netcdf file: mask.nc {
  dimensions:
    lon = 720;
    time = 1;
    lat = 361;
  variables:
    int mask(time=1, lat=361, lon=720);

    float lon(lon=720);
      :_CoordinateAxisType = "Lon";

    int time(time=1);

    float lat(lat=361);
      :_CoordinateAxisType = "Lat";

  // global attributes:
  :_CoordSysBuilder = "ucar.nc2.dataset.conv.DefaultConvention";
}
```

I tried to keep the file as simple as possible.

**Comment by ChrisBarker-NOAA** [comment]
map_from_rectangular_grid_nc_file is designed to work with 2D lat and lon -- not really required for a rectangular grid, but that's the format it was tested with.

But it's a pretty small function, we should be able to make it work with with 1D.


But perhaps it's time to take a step back: what are you trying to accomplish here? There may be a better way.

What model(s) are you working with?
What data do you have for shoreline?

Are you trying to run GNOME for a particular region? or making a system to do different regions "on the fly"?

**Comment by moisespr123** [comment]
I was trying to generate the map that PyGnome uses from a standard netCDF file rather than having to use libgoods. Just experimenting in this case.

To the last question, yes, there's code that does NetCDF files on the fly, because the global files are still 0-360 so they would need to be changed anyway to keep using the current inputs which accept lon values from -180 to 180. Backend is doing the 0-360 global to regional conversion on-the-fly based on the PyGnome input.

**Comment by moisespr123** [comment]
> ```
> model.movers += gs.PyCurrentMover([curr_mover_nc_file1,
>                                    curr_mover_nc_file2,
>                                    ...
>                                    ])
> ```
> 
> should do it

@ChrisBarker-NOAA , regarding this, does PyGnome works with files that contains u and v separately?

 Example:

```
model.movers += gs.PyCurrentMover([curr_u1.nc, curr_v1.nc, 
                                  curr_u2.nc, ,curr_v2.nc...])
```

This is another reason why I'm creating a file that contains both parameters in the same file. If it works separately, I can skip this step too.

**Comment by jay-hennen** [comment]
> > ```
> > model.movers += gs.PyCurrentMover([curr_mover_nc_file1,
> >                                    curr_mover_nc_file2,
> >                                    ...
> >                                    ])
> > ```
> > 
> > 
> > should do it
> 
> @ChrisBarker-NOAA , regarding this, does PyGnome works with files that contains u and v separately?
> 
> Example:
> 
> ```
> model.movers += gs.PyCurrentMover([curr_u1.nc, curr_v1.nc, 
>                                   curr_u2.nc, ,curr_v2.nc...])
> ```
> 
> This is another reason why I'm creating a file that contains both parameters in the same file. If it works separately, I can skip this step too.

It is possible to do separate files for U and V but it is pretty advanced usage. Especially if they are on the same grid I would not bother and put them in the same file instead.

**Comment by moisespr123** [comment]
> > > ```
> > > model.movers += gs.PyCurrentMover([curr_mover_nc_file1,
> > >                                    curr_mover_nc_file2,
> > >                                    ...
> > >                                    ])
> > > ```
> > > 
> > > 
> > > should do it
> > 
> > 
> > @ChrisBarker-NOAA , regarding this, does PyGnome works with files that contains u and v separately?
> > Example:
> > ```
> > model.movers += gs.PyCurrentMover([curr_u1.nc, curr_v1.nc, 
> >                                   curr_u2.nc, ,curr_v2.nc...])
> > ```
> > 
> > 
> > This is another reason why I'm creating a file that contains both parameters in the same file. If it works separately, I can skip this step too.
> 
> It is possible to do separate files for U and V but it is pretty advanced usage. Especially if they are on the same grid I would not bother and put them in the same file instead.

Yes, currently I'm merging both parameters to a single file.

**Comment by ChrisBarker-NOAA** [comment]
On Mon, Feb 1, 2021 at 12:35 PM Moises Cardona <notifications@github.com>
wrote:

> I was trying to generate the map that PyGnome uses from a standard netCDF
> file rather than having to use libgoods. Just experimenting in this case.
>
To clarify:

Under the hood, a "Map" can be anything that provides the methods GNOME
needs. This is specified in the GNOME Map class in:

https://github.com/NOAA-ORR-ERD/PyGnome/blob/py23/py_gnome/gnome/maps/map.py

We currently have two implementations:

1) is very simple -- all water, no land, so easy to implement :-)

2) A raster map (RasterMap class) with a pretty complex implementation: it
has nested resolutions of rasters, so that elements are far from land can
be checked quickly with a low-res raster, and then, if near land, a
higher-resolution raster can be used.

These rasters can be built from vector data (polygons) -- that's what the
MapFromBNA class does. (note: that really  should be MapFromPolygons -- and
be able to use geojson, shapefiles, etc..... PRs welcome.)

A key point is that that raster used for the maps is usually a lot higher
resolution than you'd use for a hydrodynamic model grid.

However sometimes you do want to make a map that matches the hydrodynamic
model grid. Which is what: `map_from_regular_grid` and
`map_from_regtangular_grid` do. (or might do -- poorly tested).

So: if you want a map made from your hydrodynamic grid -- take a look at
the various functions (and related) above.

If you want to make your own raster map completely on your own, then you
could probably use `map_from_rectangular_grid` -- and read the netcdf file
yourself.

> To the last question, yes, there's code that does NetCDF files on the
fly, because the global files are still 0-360 so they would need to be
changed anyway to keep using the current inputs which accept lon values
from -180 to 180.

what other inputs do you have? it might be easier to convert them :-)

@jay-hennen: I recall some recent work with shifting the coords on the fly
-- could that help here?

HTH,

-CHB

-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov
