### ISSUE TITLE
1

### ISSUE THREAD

**Issue by fSohrabi75** [NOAA-ORR-ERD/PyGnome#80]

**Comment by ChrisBarker-NOAA** [comment]
hmm -- it seems to be using a Wind object when it's expecting a water object. But I can't see from your script why that would be. 

first suggestion would be to try the similer approach used in:

https://github.com/NOAA-ORR-ERD/PyGnome/blob/master/py_gnome/scripts/script_weathering_run/script_weathering_run.py

the model should be able to "hook up" everything for you, so you dont' have to set all the various environment objects by hand. (you may want to set them by hand if you need more control, but the "usual" case can be simple)

Also -- it should be able to find the wind you are using in the GridWindMover -- if you want to use those same winds for weathering (usually the case).

BTW, does this script run properly?

https://github.com/NOAA-ORR-ERD/PyGnome/blob/master/py_gnome/scripts/script_weatherers/script_weatherers.py

if not, then it's a bug / change in our code. If so, then try to see what you've done differently.

**Comment by farzanehashemabadi** [comment]
Dear. ChrisBarker
I run the script_weatherer and received thie Error:


/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/python2.7                                                                             /site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/__init__.py:52: UserWa                                                                             rning: Version 2.6.3 of unit_conversion package is required, but actual version                                                                              in module is 2.10.1
  warnings.warn(msg)
images_dir is: /home/farzaneh.hashemabadi.student/PyGnome/py_gnome/scripts/scrip                                                                             t_weatherers/images
removing... /home/farzaneh.hashemabadi.student/PyGnome/py_gnome/scripts/script_w                                                                             eatherers/images
initializing the model
removed script_weatherers.nc
removed script_weatherers.nc
adding a spill
querying DB:
Oil.name ==  'ALASKA NORTH SLOPE (MIDDLE PIPELINE, 1997)'
adding a RandomMover:
adding a wind mover:
adding weatherers and cleanup options:
/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/python2.7                                                                             /site-packages/scipy/optimize/minpack.py:787: OptimizeWarning: Covariance of the                                                                              parameters could not be estimated
  category=OptimizeWarning)
Traceback (most recent call last):
  File "script_weatherers.py", line 158, in <module>
    model.full_run()
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/model.py", lin                                                                             e 1123, in full_run
    results = self.step()
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/model.py", lin                                                                             e 1053, in step
    output_info = self.output_step(isValid)
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/model.py", lin                                                                             e 1058, in output_step
    output_info = self.write_output(isvalid)
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/model.py", lin                                                                             e 992, in write_output
    output = outputter.write_output(self.current_time_step)
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/outputters/net                                                                             cdf.py", line 681, in write_output
    super(NetCDFOutput, self).write_output(step_num, islast_step)
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/outputters/out                                                                             putter.py", line 337, in write_output
    compute_surface_concentration(sc, self.surface_conc)
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/utilities/surf                                                                             ace_concentration.py", line 26, in compute_surface_concentration
    surface_conc_kde(sc)
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/utilities/surf                                                                             ace_concentration.py", line 74, in surface_conc_kde
    kernel = gaussian_kde(xy,weights=mass_for_kernel/mass_for_kernel.sum())
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/scipy/stats/kde.py", line 208, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/scipy/stats/kde.py", line 540, in set_bandwidth
    self._compute_covariance()
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/scipy/stats/kde.py", line 552, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/home/farzaneh.hashemabadi.student/.conda/envs/farzane.hashemabadi/lib/p                                                                             ython2.7/site-packages/scipy/linalg/basic.py", line 974, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.LinAlgError: singular matrix

**Comment by farzanehashemabadi** [comment]
I have a question from your first suggestion, can I have use my GridWindMover in environment wind object??
if yes, how can I use it?
