### ISSUE TITLE
How to Import ROMS current netcdf file in Pygnome

### ISSUE THREAD

**Issue by DoctorHamzeh** [NOAA-ORR-ERD/PyGnome#92]
Hello Dears,
As it seems, PyCurrentMover class is considered for importing current netcdf files from GNOME Online Oceanographic Data Server in which specific global attributes and variables names are according to GNOME acceptable format.
However, for an output netcdf current file from a ROMS model installed in a linux os, is there any function for direct importing of netcdf file? Whats is the best method to import this file to Pygnome?
Thank you in advance

**Comment by ChrisBarker-NOAA** [comment]
Sorry for the confusion:

We have two different Gridded Current Mover implementations:

GridCurrentMover: The "old" one, written largely in C++ -- it is needed to support some not-quite conforming grids that we need, and get from GOODS. It only understands "GNOME format" netcdf files -- as you say, with specific variable names and metadata.

PyCurrentMover is the newer, pure-Python implementation. It support the "GNOME format"
 netcdf files, as well as (theoretically) any CF and SGRID or UGRID compliant netcdf files (and many semi-compliant files). 

ROMS uses an SGRID (http://sgrid.github.io/sgrid/), so ideally, should use the SGRID conventions.

I've lost track a bit of what ROMS is outputting by default, but it didn't used to be SGRID compliant.

However, you can also tell GNOME a bit about the file, and then it should be able to load it.

The PyCurrentMover takes an optional grid_topology parameter, where you can specify what variable hold the grid topology.

This is minimally documented here:

https://gnome.orr.noaa.gov/doc/pygnome/env_obj/examples.html?highlight=grid_topology

with an example here:

https://gnome.orr.noaa.gov/doc/pygnome/env_obj/env_obj_examples.html?highlight=grid_topology

For all the grid "parts" see the (also minimal :-( ) documentation for the gridded package:

https://noaa-orr-erd.github.io/gridded/non_conforming_data.html#if-your-files-conform-to-the-underlying-data-model

If you can't figure it out, post and (ideally small!) sample file, and we can help.

Also: Documentation PRs excepted -- and "out of the box ROMS" example would be a good one to have in the docs.

-CHB

**Comment by civilandenvironmentalengineer** [comment]
Thank you Dr.Barker for complete response to this issue.
For example, would you please guide me how to use PyCurrentMover  class for importing this netcdf current file:
[http://geoport.whoi.edu/thredds/dodsC/examples/bora_feb.nc](url)

**Comment by ChrisBarker-NOAA** [comment]
There is an issue with the "padding" for a staggered grid:

http://sgrid.github.io/sgrid/

hard to tell from the header exactly what's goin on.

Can you enclose (Or post somewhere) an actual netcdf file -- that will make it easier to debug.

@jay-hennen: any ideas?

**Comment by Rintei** [comment]
Has the issue been resolved(ROMS result -> GNOME input)? I tried to solve it using the function of PyMovers, but the addresses you linked above did not work, so I can't compare them by checking examples. Please reply if that had already  been resolved.

Thank you in advance.

**Comment by ChrisBarker-NOAA** [comment]
As it happens, we are working on some of these issues right now.

If you could provide a link to a data file (ideally pretty small -- e.g. only a couple timesteps) -- we can figure it out.

@jay-hennen:  any ideas here -- does this look like ROMS files we have already?

**Comment by jay-hennen** [comment]
Sorry I missed this issue. I think your `grid_topo` definition is incorrect. The 'nodes' of a ROMS grid are the psi points. Try defining node_lon as lon_psi and node_lat as lat_psi and see if that helps. Alternatively, don't pass in a topology at all, because it *should* be able to autodetect those names.

**Comment by Rintei** [comment]
Thanks for the quick reply. Since I can provide you with the file you requested, I shared a link with limited access(100 counted access times). If you can't access the link, please let us know again.

>     roms_mapping = {'node_lon': 'lon_psi','node lat': 'lat_psi'}
>     u_mover = PyCurrentMover(roms_file,
>                              grid_topology=roms_mapping)
>     model.movers += u_mover

data file link : [http://naver.me/51Q2w2av](url)

I've tried as you advised, but following error:

Traceback (most recent call last):
  File "PyGnome03_1.py", line 189, in <module>
    model = make_model(x)
  File "PyGnome03_1.py", line 67, in make_model
    u_mover = PyCurrentMover(roms_file,
  File "\py_gnome\gnome\movers\py_current_movers.py", line 99, in __init__
    self.current = GridCurrent.from_netCDF(filename=self.filename,
  File "\py_gnome\gnome\environment\gridded_objects_base.py", line 884, in from_netCDF
    var.init_from_netCDF(*args, **kwargs)
  File "\py_gnome\gnome\environment\gridded_objects_base.py", line 861, in init_from_netCDF
    self.__init__(name=name,
  File "\py_gnome\gnome\environment\environment_objects.py", line 246, in __init__
    self.angle = Variable(name='angle',
  File "\py_gnome\gnome\environment\gridded_objects_base.py", line 424, in __init__
    super(Variable, self).__init__(*args, **kwargs)
  File ".conda\envs\gnome\lib\site-packages\gridded\variable.py", line 114, in __init__
    self.data = data
  File ".conda\envs\gnome\lib\site-packages\gridded\variable.py", line 371, in data
    raise ValueError("Data/grid shape mismatch: Data shape is {0}, "
ValueError: Data/grid shape mismatch: Data shape is (720, 700), Grid shape is (719, 699)

**Comment by jay-hennen** [comment]
Can you post the ncdump -h of the file you are trying to use? It is too large for us to download.

**Comment by Rintei** [comment]
> Can you post the ncdump -h of the file you are trying to use? It is too large for us to download.

I put the "ncdump_result.log" file on the linked drive.
thank you

**Comment by jay-hennen** [comment]
I suggest you can remove the `roms_mapping = ` line from your code and see what happens. As far as I can tell that file should work with no special arguments required.

**Comment by Rintei** [comment]
> I suggest you can remove the line from your code and see what happens. As far as I can tell that file should work with no special arguments required.`roms_mapping = `

Traceback (most recent call last):
  File "PyGnome03_2.py", line 195, in <module>
    for step in model:
  File "gnome\model.py", line 1163, in __next__
    return self.step()
  File "gnome\model.py", line 1083, in step
    (msgs, isValid) = self.check_inputs()
  File "gnome\model.py", line 1612, in check_inputs
    bounds = mover.get_bounds()
  File "gnome\movers\py_current_movers.py", line 206, in get_bounds
    longs, lats = self.get_lat_lon_data()
  File "gnome\movers\py_current_movers.py", line 200, in get_lat_lon_data
    return lons.reshape(-1), lats.reshape(-1)
  File "src\netCDF4\_netCDF4.pyx", line 4358, in netCDF4._netCDF4.Variable.__getattr__
  File "src\netCDF4\_netCDF4.pyx", line 4164, in netCDF4._netCDF4.Variable.getncattr
  File "src\netCDF4\_netCDF4.pyx", line 1445, in netCDF4._netCDF4._get_att
  File "src\netCDF4\_netCDF4.pyx", line 1927, in netCDF4._netCDF4._ensure_nc_success
AttributeError: NetCDF: Attribute not found

 
> EDIT: Although, nevermind that. It won't work because of depth related bugs that I am working on fixing right now

So, Didn't work PyGnome by input data of 3D layers? I'm confused by your reply. Please clarify whether it is a compatibility issue with the result of the ROMS model, or just a happening because PyGnome is under development. If the latter is your opinions, then let's come up with the ideas need to apply them.

Thanks.

**Comment by ChrisBarker-NOAA** [comment]
Closing due to inactivity -- please post a new issue if you have further questions about this topic.
