### ISSUE TITLE
Help Loading an Older Python2.7 Version of GNOME

### ISSUE THREAD

**Issue by whitij** [NOAA-ORR-ERD/PyGnome#94]
Several years ago (~2019) I had GNOME installed and working on a project with TAP. While I hear you are upgrading to Python3, I'm still planning to use this Python2.7 version of GNOME for the time being, since it was working with some custom TAP code.

So that being the context, I'm running into some errors with the install. I'm using Anaconda 2.7, configured the channels, created a gnome environment and installed libraries from conda_requirements.txt. However, I'm running into some errors with gdal, though I can list packages and see gdal=2.2.2 installed. I've tried mucking around with the PYTHONPATH and system environmental variables but I'm not getting anywhere. Can you please look at the trace below and let me know if you have any suggestions?

Traceback (most recent call last):
  File "C:\Users\git\fearless\RunPyGnome.py", line 5, in <module>
    from gnome.scripting import surface_point_line_spill
  File "c:\users\documents\projects\arpa-e\gnomefiles\pygnome-master\py_gnome\gnome\__init__.py", line 116, in <module>
    from . import (map,
  File "c:\users\documents\projects\arpa-e\gnomefiles\pygnome-master\py_gnome\gnome\map.py", line 21, in <module>
    from osgeo import ogr
  File "C:\Users\AppData\Local\Continuum\anaconda2\envs\gnome\lib\site-packages\osgeo\__init__.py", line 25, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\AppData\Local\Continuum\anaconda2\envs\gnome\lib\site-packages\osgeo\__init__.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.

**Comment by ChrisBarker-NOAA** [comment]
Darn. 

I thought we'd gotten rid of the dependency on gdal. ANd looking at master now, I think we did -- thte import lines are commented out.

So make sure you've got latest master -- it should work with py2.7

Finally: it will probably be trivial to port your scripts to py3 -- probably worth it. The future package can help with the transition:

https://python-future.org/index.html

-CHB

**Comment by whitij** [comment]
Thanks for the tips Chris. We are trying to get it running in py2.7 first so the rest of the project can get moving, then we will likely port to py3.

So after pulling master I had some issues running installing the conda_requirements.txt and ended up installing the libraries individually using conda. However, I'm stuck at another import error, this time around "UnsupportedFields". I'm showing as having colander v1.0 installed from the pypi channel. Have you seen this before?

Traceback (most recent call last):
  File "runpygnome.py", line 9, in <module>
    from gnome.scripting import surface_point_line_spill
  File "c:\users\whit162\git\fearless\pygnome-master\py_gnome\gnome\__init__.py", line 116, in <module>
    from . import (environment,
  File "c:\users\whit162\git\fearless\pygnome-master\py_gnome\gnome\environment\__init__.py", line 5, in <module>
    from .environment import Environment, env_from_netCDF, ice_env_from_netCDF
  File "c:\users\whit162\git\fearless\pygnome-master\py_gnome\gnome\environment\environment.py", line 20, in <module>
    from gnome.persist import base_schema
  File "c:\users\whit162\git\fearless\pygnome-master\py_gnome\gnome\persist\__init__.py", line 6, in <module>
    from gnome.persist import base_schema, extend_colander, validators
  File "c:\users\whit162\git\fearless\pygnome-master\py_gnome\gnome\persist\base_schema.py", line 12, in <module>
    from colander import (SchemaNode, deferred, drop, required, Invalid, UnsupportedFields,
ImportError: cannot import name UnsupportedFields

**Comment by ChrisBarker-NOAA** [comment]
You might try colander less than 2:

`conda install colander<2`

or

`conda install colander=1.7`

I've got colander 1.7.0 working with my py2 setup.

As a rule, for conda:

It works better if you pass in al lthe requirements at once
and

It's best to use conda first, and only PiPy if you really need to -- and you should be able to get everything for GNOME from conda, tough yuo will need the conda-forge channel, and maybe the NOAA-ORR-ERD channel.

sounds like you are close!

Here's my python 2 setup -- it's a Mac, so maybe slighlty different, but most of it should be there:

```
# packages in environment at /Users/chris.barker/miniconda3/envs/gnome_p2:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appnope                   0.1.0           py27h8c360ce_1001    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
awesome-slugify           1.6.5                      py_5    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.5                        py_1    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
brotlipy                  0.7.0           py27h0b31af3_1000    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.17.1               h0d85af4_1    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
cell_tree2d               0.3.0           py27h4f17bb1_1001    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
cffi                      1.14.0           py27h356ff06_0    conda-forge
cftime                    1.0.4.2          py27h3b54f70_0    conda-forge
chardet                   3.0.4           py27h8c360ce_1006    conda-forge
colander                  1.7.0                    py27_0  
configparser              3.7.3            py27h8c360ce_2    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
coverage                  5.0.4            py27h89ed719_0    conda-forge
cryptography              2.8              py27hab9f8d5_2    conda-forge
curl                      7.76.1               h06286d4_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.25.2                   py27_1    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
docutils                  0.16             py27h8c360ce_1    conda-forge
entrypoints               0.3             py27h8c360ce_1001    conda-forge
enum34                    1.1.10           py27h8c360ce_1    conda-forge
expat                     2.3.0                he49afe7_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
funcsigs                  1.0.2                      py_3    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
futures                   3.3.0            py27h8c360ce_1    conda-forge
geojson                   1.3.2                    py27_1    NOAA-ORR-ERD
geos                      3.8.1                h4a8c4bd_0    conda-forge
gettext                   0.19.8.1          haf92f58_1004    conda-forge
gitdb2                    2.0.6                      py_0    conda-forge
gitpython                 2.1.11                     py_0    conda-forge
glib                      2.66.1               h39b9ebd_0    conda-forge
gridded                   0.2.5                    py27_0    conda-forge
gsw                       3.0.3                    py27_1    NOAA-ORR-ERD
hdf4                      4.2.13            hefd3b78_1005    conda-forge
hdf5                      1.10.3            hfa1e0ec_1001    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.5.0            py27h8c360ce_1    conda-forge
importlib_metadata        1.5.0                         1    conda-forge
ipaddress                 1.0.23                     py_0    conda-forge
ipykernel                 4.10.0                   py27_0    conda-forge
ipython                   5.8.0                    py27_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
iso8601                   0.1.10                   py27_0    NOAA-ORR-ERD
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
jsonschema                3.2.0            py27h8c360ce_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.4                    py27_1    conda-forge
jupyter_console           5.2.0                    py27_1    conda-forge
jupyter_core              4.6.3            py27h8c360ce_1    conda-forge
kiwisolver                1.1.0            py27h5cd23e5_1    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  11.1.0          default_he082bbe_0    conda-forge
libcurl                   7.76.1               h8ef9fac_1    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgd                     2.1.1                         5    NOAA-ORR-ERD
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_2    conda-forge
libnetcdf                 4.6.1             hc60090f_1010    conda-forge
libnghttp2                1.43.0               h07e645a_0    conda-forge
libopenblas               0.3.7                hd44dcd8_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     13.2                 h052a64a_2    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libssh2                   1.9.0                h52ee1ee_6    conda-forge
libtiff                   4.2.0                h7c11950_1    conda-forge
libwebp-base              1.2.0                h0d85af4_2    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
mapbox_earcut             0.12.10          py27h04f5b5a_0    NOAA-ORR-ERD
markupsafe                1.1.1            py27h89ed719_1    conda-forge
matplotlib                2.2.5                h694c41f_3    conda-forge
matplotlib-base           2.2.5            py27h11da6c2_1    conda-forge
mistune                   0.8.4           py27h89ed719_1001    conda-forge
more-itertools            5.0.0                      py_0    conda-forge
mysql-common              8.0.23               h694c41f_1    conda-forge
mysql-libs                8.0.23               hbeb7981_1    conda-forge
nbconvert                 5.6.1                    py27_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nbsphinx                  0.3.5                      py_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
netcdf4                   1.4.1            py27hac939d9_3    conda-forge
nose                      1.3.7           py27h8c360ce_1004    conda-forge
notebook                  5.7.8                    py27_1    conda-forge
nspr                      4.30                 hcd9eead_0    conda-forge
nss                       3.64                 h31e2bf1_0    conda-forge
numpy                     1.16.5           py27hde6bac1_0    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandoc                    2.13                 h0d85af4_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pathlib2                  2.3.5            py27h8c360ce_1    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5           py27h8c360ce_1001    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
progressbar               2.3                      py27_0    NOAA-ORR-ERD
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
psutil                    5.7.0            py27h89ed719_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
py_gd                     0.1.5                    py27_0    NOAA-ORR-ERD
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pynucos                   2.10.1             pyhd8ed1ab_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    1.9.4                    py27_1    NOAA-ORR-ERD
pyqt                      5.12.3           py27he22c54c_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py27h89ed719_1    conda-forge
pyshp                     1.2.12                     py_2    conda-forge
pysocks                   1.7.1            py27h8c360ce_1    conda-forge
pytest                    4.6.4                    py27_0    conda-forge
pytest-cov                2.11.0             pyh44b312d_0    conda-forge
pytest-timeout            1.4.2              pyh9f0ad1d_0    conda-forge
python                    2.7.15          h8e446fc_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                2.7                     1_cp27m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyzmq                     19.0.0           py27h74110c0_1    conda-forge
qt                        5.12.9               h126340a_4    conda-forge
qtconsole                 4.7.7              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
regex                     2016.06.24               py27_0    NOAA-ORR-ERD
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scandir                   1.10.0           py27h89ed719_1    conda-forge
scipy                     1.2.1            py27hab3da7d_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
shapely                   1.7.0            py27h57c807a_2    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.6.1              pyh44b312d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     4.0.0              pyh44b312d_0    conda-forge
smmap2                    3.0.1                      py_0    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
sphinx                    1.8.5                    py27_0    conda-forge
sphinx_rtd_theme          0.5.2              pyhd8ed1ab_1    conda-forge
sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
sqlite                    3.35.5               h44b9ce1_0    conda-forge
subprocess32              3.5.4            py27h0b31af3_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3            py27h8c360ce_1    conda-forge
testfixtures              4.1.2                    py27_0    NOAA-ORR-ERD
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tornado                   5.1.1           py27h1de35cc_1000    conda-forge
traitlets                 4.3.3            py27h8c360ce_1    conda-forge
translationstring         1.4                pyh9f0ad1d_0    conda-forge
trimesh                   3.9.15             pyh44b312d_0    conda-forge
typing                    3.7.4.1          py27h8c360ce_1    conda-forge
unidecode                 1.1.2              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1              pyh9f0ad1d_3    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zipp                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.9                h582d3a0_0    conda-forge
```

**Comment by whitij** [comment]
Thank you Chris, I'm up and running now! Upgrading colander to 1.7.0 did the trick and having your list of packages was very helpful.
