### ISSUE TITLE
installing pygnome/oillibrary in ubuntu 20.04_issues 

### ISSUE THREAD

**Issue by PrasadSJ** [NOAA-ORR-ERD/PyGnome#95]
Dear Peers, 

i encountered with an error as follow, while installing Oillibrary, Kindly suggest to rectify this  
thanks in advance 

-------------------------------------------------------------

**OilLibrary database generation failed**
Traceback (most recent call last):
  File "setup.py", line 208, in <module>
    zip_safe=False,
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_py')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 160, in run
    init_db()
  File "setup.py", line 88, in init_db
    import oil_library.initializedb
  File "/home/sjprasad/pythongnomemay52021/OilLibrary/oil_library/__init__.py", line 12, in <module>
    from sqlalchemy import create_engine
ImportError: No module named sqlalchemy

**Comment by ChrisBarker-NOAA** [comment]
It looks like the requirements for oil_library didn't get installed.

Make sure to install them:

conda install --file conda_requirements.txt

NOTE: this is the conda_requirements.txt file in the OilLibrary project

BTW: we are VERY close to fully Python3 versions of everything. It's probably a better idea to use the develop branch of both py_gnome and oil_library, and run them using Python 3.8

We'll get that pushed to the master branches soon.

**Comment by PrasadSJ** [comment]
Thank you Dr.Chris. i could able to install Oil library, 
1. but obtained the following error .
--------------------------
running install
running bdist_egg
running egg_info
error: [Errno 13] Permission denied: 'oil_library.egg-info'
--------------------------------
2. It is good that pygnome and oil library are getting renewed to py3.8. In that case, have i to uninstall this complete (existing) set up(that is py2.7, conda and other dependent package) ?

Pls suggest on the above 2 queries

Thanks

**Comment by PrasadSJ** [comment]
Dear Dr.Chris, 

Please suggest on this also. 

3. Even after installing pygnome and its dependencies, i am getting the following error
-----------------------------------------------------------------------
(gnome) sjprasad@sjprasad-VirtualBox:~/pythongnomemay52021/PyGnome/py_gnome/scripts/script_boston$ python script_boston.py
Traceback (most recent call last):
  File "script_boston.py", line 20, in <module>
    import gnome.scripting as gs
ImportError: No module named gnome.scripting
---------------------------------------------------------------------------------
Kindly suggest 

Thanks

**Comment by ChrisBarker-NOAA** [comment]
should all be fixed by now ...
