### ISSUE TITLE
Error using Tamoc package - script_tamoc.py

### ISSUE THREAD

**Issue by DoctorHamzeh** [NOAA-ORR-ERD/PyGnome#96]
Hello,
After  running  script_tamoc.py in PyGNOME, there is an error "AttributeError: 'NoneType' object has no attribute 'all_array_types'
"
in these commands: 
for step in model:
     m=model.get_spill_property('age')
model.full_run()
Thank you in advance for any suggestion.

**Comment by jay-hennen** [comment]
Can you post the entire traceback please?

**Comment by civilandenvironmentalengineer** [comment]
-- Initializing the Model         --

-- Adding a Map                   --

-- Adding Image Outputters        --

-- Adding NetCDF Outputter        --

-- Adding a Point Spill           --

-- Adding Currents                --

-- Adding Particle Diffusion      --

-- Adding Particle Rise Velocity  --

-- Adding Weathering              --

-- RUNNING TAMOC-GNOME SIMULATION --
Traceback (most recent call last):
  File "/home/mirkhalili/Desktop/gnome_train/script_tamoc/script_tamoc.py", line 249, in <module>
    model = run_model(model)
  File "/home/mirkhalili/Desktop/gnome_train/script_tamoc/script_tamoc.py", line 237, in run_model
    for step in model:
  File "/home/mirkhalili/anaconda2/envs/eram/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/model.py", line 1103, in next
    return self.step()
  File "/home/mirkhalili/anaconda2/envs/eram/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/model.py", line 1017, in step
    self.setup_model_run()
  File "/home/mirkhalili/anaconda2/envs/eram/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/model.py", line 744, in setup_model_run
    array_types.update(item.all_array_types)
  File "/home/mirkhalili/anaconda2/envs/eram/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/spill/spill.py", line 180, in all_array_types
    arr.update(self.release.all_array_types)
AttributeError: 'NoneType' object has no attribute 'all_array_types'

Process finished with exit code 1

**Comment by gab1092** [comment]
Hello! @DoctorHamzeh I'm trying to run the tamoc with gnome but I have the same error. Were you can solved the problem? In case that answer is yes, could you help me please?
Thank you

**Comment by ChrisBarker-NOAA** [comment]
Note to all:

there have been a number of changes in both PyGNOME and TAMOC in the last months. So the `script_tamoc.py` example may not work.

We (NOAA) will be working on improving  TAMOC / PyGNOME integration  -- probably starting next month.

In the meantime, it would be great if any folks that want to use them together can help out.

Even if are not up to getting into the TAMOC or PyGNOME code itself, testing and use cases would be great. I've started an issue here to discuss: #105

**Comment by gab1092** [comment]
@ChrisBarker-NOAA  Thank you for the answer, I will try to use some data from TAMOC to run a simulation in GNOME, and I will be waiting for the news of PyGNOME.

**Comment by ChrisBarker-NOAA** [comment]
Closing due to inactivity -- please post a new issue if you have further questions about this topic.
